// export const DESPACITO_CHOREO = {
//   despacito: [
//     { time: 0.0, move: "idle" },
//     { time: 4.0, move: "samba_basic" },
//     { time: 8.0, move: "samba_side" },
//     { time: 12.0, move: "samba_bounce" },
//     { time: 17.0, move: "samba_basic" },
//     { time: 22.0, move: "wave" },
//     { time: 26.0, move: "sidetoside" },
//     { time: 30.0, move: "snake" },
//     { time: 35.0, move: "samba_volta" },
//     { time: 40.0, move: "samba_side" },
//     { time: 45.0, move: "kickstep" },
//     { time: 50.0, move: "samba_basic" },
//     { time: 55.0, move: "locking" },
//     { time: 60.0, move: "runningman" },
//     { time: 65.0, move: "samba_bounce" },
//     { time: 70.0, move: "wave" },
//     { time: 75.0, move: "sidetoside" },
//     { time: 80.0, move: "snake" },
//     { time: 85.0, move: "samba_volta" },
//     { time: 90.0, move: "samba_side" },
//     { time: 95.0, move: "kickstep" },
//     { time: 100.0, move: "samba_basic" },
//     { time: 105.0, move: "locking" },
//     { time: 110.0, move: "runningman" },
//     { time: 115.0, move: "samba_bounce" },
//     { time: 120.0, move: "sidetoside" },
//     { time: 125.0, move: "snake" },
//     { time: 130.0, move: "wave" },
//     { time: 135.0, move: "kickstep" },
//     { time: 140.0, move: "samba_basic" },
//     { time: 145.0, move: "samba_side" },
//     { time: 150.0, move: "samba_bounce" },
//     { time: 155.0, move: "runningman" },
//     { time: 160.0, move: "locking" },
//     { time: 165.0, move: "wave" },
//     { time: 170.0, move: "idle" }
//   ]
// };
